# Generated by Django 4.2.1 on 2023-06-07 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitems",
            options={
                "ordering": ["category", "title"],
                "permissions": (("add_menu_items", "Add Menu Items"),),
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
            },
        ),
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
    ]
