# Generated by Django 4.2.7 on 2023-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitems",
            name="category",
            field=models.CharField(
                choices=[
                    ("1", "Appetizer"),
                    ("2", "Dessert"),
                    ("3", "Entree"),
                    ("4", "Drink"),
                    ("5", "Side Order"),
                ],
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
