# Generated by Django 4.2.3 on 2023-07-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                choices=[
                    ("1", "Appetizer"),
                    ("2", "Dessert"),
                    ("3", "Entree"),
                    ("4", "Drink"),
                    ("5", "Side Order"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
