# Generated by Django 4.2.3 on 2023-08-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_remove_category_slug_alter_category_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="menuitems",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="API.menuitems"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="API.order"
            ),
        ),
    ]
