# Generated by Django 4.2.7 on 2023-12-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_alter_menuitems_category_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="littlelemoner",
            name="home_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="littlelemoner",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="API.customerpayment",
            ),
        ),
    ]
