# Generated by Django 4.2.1 on 2023-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_alter_menuitems_options_remove_orderitem_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
