# Generated by Django 4.2.3 on 2023-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_alter_cart_menuitems_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
